title: Deep Learning Blog
email: zafarullahmahmood@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogs by Zafarullah Mahmood (zaffnet) zafarullahmahmood@gmail.com Covers Deep Neural Networks and image recognition
baseurl: ""
url: "https://zaffnet.github.io"
twitter_username: zaffnet
github_username:  zaffnet
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
highlighter: pygments
