title: Deep Learning Blog
email: zafarullahmahmood@gmail.com
description: Blogs by Zafarullah Mahmood (zaffnet) | zafarullahmahmood@gmail.com
baseurl: ""
url: "https://zaffnet.github.io"
twitter_username: zaffnet
github_username:  zaffnet
gems:
  - jekyll-feed
  - jekyll-gist
  - execjs
exclude:
  - Gemfile
  - Gemfile.lock
