title: Deep Learning Blog
email: zafarullahmahmood@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Deep Learning Tutorial
baseurl: ""
url: "https://zaffnet.github.io"
twitter_username: zaffnet
github_username:  zaffnet
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
hilighter: pygments
